## 배열 연산 - 브로드 캐스팅
- vectorized 사용 
- 일반적으로 Numpy의 범용 함수 (Ufunc) 을 통해 구현
- 배열 요소에 대한 반복적 계산을 효율적으로 사용 

In [3]:
import numpy as np

In [5]:
a1 = np.array([1,2,3]) 
print(a1 + 5)

[6 7 8]


In [10]:
a2 = np.arange(1,10).reshape(3,3)
print(a1, "\n")
print(a2, "\n")
print(a1 + a2)

[1 2 3] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [11]:
b2 = np.array([1,2,3]).reshape(3,1)

print(a1, "\n")
print(b2, "\n")
print(a1 + b2)

[1 2 3] 

[[1]
 [2]
 [3]] 

[[2 3 4]
 [3 4 5]
 [4 5 6]]


##  산술 연산 (arithmetic operators) 

- '+' np.add 덧셈
- '-' np.substract 뺄셈
- '-' np.negative 단항 음수
- '*' np.multiply 곱셈
- '/' np.divide 나눗셈
- '//' np.floor_devide 나눗셈 내림
- '**' np.power 제곱, 지수연산
- '%'np.mod 나머지 연산 





In [18]:
a1 = np.arange(1,10)
print(a1, "\n")
print(a1 + 1, "\n")
print(np.add(a1,10), "\n")
print(np.subtract(a1, 10), "\n")
print(-a1, "\n") # = print(np.negative(a1))
print(np.multiply(a1, 2),"\n")
print(np.divide(a1, 2), "\n")
print(np.floor_divide(a1, 2),"\n")
print(np.power(a1, 2),"\n")
print(np.mod(a1, 2),"\n")

[1 2 3 4 5 6 7 8 9] 

[ 2  3  4  5  6  7  8  9 10] 

[11 12 13 14 15 16 17 18 19] 

[-9 -8 -7 -6 -5 -4 -3 -2 -1] 

[-1 -2 -3 -4 -5 -6 -7 -8 -9] 

[ 2  4  6  8 10 12 14 16 18] 

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[0 1 1 2 2 3 3 4 4] 

[ 1  4  9 16 25 36 49 64 81] 

[1 0 1 0 1 0 1 0 1] 



In [20]:
a1 = np.arange(1,10)
print(a1, "\n")

b1 = np.random.randint(1, 10, size=9)
print(b1, "\n")
print(a1 + b1,"\n")
print(a1 - b1, "\n")
print(a1 * b1, "\n")
print(a1/b1, "\n")
print(a1**b1, "\n")
print(a1//b1,"\n")

[1 2 3 4 5 6 7 8 9] 

[4 6 3 5 8 7 9 9 2] 

[ 5  8  6  9 13 13 16 17 11] 

[-3 -4  0 -1 -3 -1 -2 -1  7] 

[ 4 12  9 20 40 42 63 72 18] 

[0.25       0.33333333 1.         0.8        0.625      0.85714286
 0.77777778 0.88888889 4.5       ] 

[        1        64        27      1024    390625    279936  40353607
 134217728        81] 

[0 0 1 0 0 0 0 0 4] 



In [23]:
a2 = np.arange(1,10).reshape(3,3)
b2 = np.random.randint(1,10, size=(3,3))
print(a2)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 6]
 [1 3 4]
 [9 2 4]]


In [24]:
print(a2 + b2, "\n")
print(a2 - b2, "\n")
print(a2 * b2, "\n")
print(a2 / b2, "\n")
print(a2 // b2, "\n")
print(a2 ** b2, "\n")
print(a2 % b2, "\n")

[[ 2  6  9]
 [ 5  8 10]
 [16 10 13]] 

[[ 0 -2 -3]
 [ 3  2  2]
 [-2  6  5]] 

[[ 1  8 18]
 [ 4 15 24]
 [63 16 36]] 

[[1.         0.5        0.5       ]
 [4.         1.66666667 1.5       ]
 [0.77777778 4.         2.25      ]] 

[[1 0 0]
 [4 1 1]
 [0 4 2]] 

[[       1       16      729]
 [       4      125     1296]
 [40353607       64     6561]] 

[[0 2 3]
 [0 2 2]
 [7 0 1]] 



In [30]:
# 절대값 함수

a1 = np.random.randint(-10, 10, size=(3,3))
print(a1)
np.absolute(a1)

# 제곱근 함수 

print(np.sqrt(a1)) # 음수 제곱근 nan으로 뜸

[[-2  7  5]
 [-6 -1  0]
 [-9 -9 -3]]
[[       nan 2.64575131 2.23606798]
 [       nan        nan 0.        ]
 [       nan        nan        nan]]


/var/folders/4f/jnlgcb9n6pg311w43wdsllwc0000gn/T/ipykernel_10817/4186405359.py:9: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


In [35]:
# 지수와 로그 함수

a1 = np.random.randint(1, 10, size=5)
print(a1, "\n")
print(np.exp(a1),"\n") # 밑이 자연상수 (e)인 지수-- e^x  
print(np.exp2(a1),"\n") # 밑이 2인 지수 -- 2^x
print(np.power(a1,2),"\n")

[6 1 2 6 4] 

[403.42879349   2.71828183   7.3890561  403.42879349  54.59815003] 

[64.  2.  4. 64. 16.] 

[36  1  4 36 16] 



In [37]:
print(a1, "\n")
print(np.log(a1),"\n") # 자연 로그
print(np.log2(a1),"\n")  # 밑 2
print(np.log10(a1),"\n") # 밑 10

[6 1 2 6 4] 

[1.79175947 0.         0.69314718 1.79175947 1.38629436] 

[2.5849625 0.        1.        2.5849625 2.       ] 

[0.77815125 0.         0.30103    0.77815125 0.60205999] 



## 삼각함수

In [39]:
t = np.linspace(0, np.pi, 3) # 균등하게 나누는 게 linspace
print(t)

print(np.sin(t),"\n")
print(np.cos(t),"\n")
print(np.tan(t),"\n")


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16] 

[ 1.000000e+00  6.123234e-17 -1.000000e+00] 

[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16] 



In [42]:
x = [-1, 0, 1]

print(x,"\n")
print(np.arcsin(x),"\n")
print(np.arccos(x),"\n")
print(np.arctan(x),"\n")

[-1, 0, 1] 

[-1.57079633  0.          1.57079633] 

[3.14159265 1.57079633 0.        ] 

[-0.78539816  0.          0.78539816] 



## 집계함수

In [46]:
a2 = np.random.randint(1, 10, size=(3,3))
print(a2,"\n")
print(a2.sum(), np.sum(a2), "\n") # 행열 구분없이 다 더한거
print(a2.sum(axis=0), np.sum(a2, axis=0), "\n") # 아래로 다 더함
print(a2.sum(axis=0), np.sum(a2, axis=1), "\n") # 옆으로 다 더함


[[7 9 3]
 [4 1 1]
 [7 1 7]] 

40 40 

[18 11 11] [18 11 11] 

[18 11 11] [19  6 15] 

