In [1]:
L = list(range(10))

L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]


[bool, str, float, int]

In [22]:
import numpy as np

x = np.arange(10)
x[1:9] # 슬라이싱 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x[1::3] # 1 = 9까지 1부터 3 간격으로 할 때 :: 사용
    

array([1, 4, 7])

In [24]:
x[5::-2] # 5부터 거꾸로 -2씩 빼서 사용

array([5, 3, 1])

In [27]:
x2 = np.array([[12, 5, 2, 4],
                [7, 6, 8, 8],
                [1, 6, 7, 7]])
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
x2_sub = x2[:2, :2]
x2_sub

[[12  5]
 [ 7  6]]


In [33]:
x2_sub[0,0] = 99 # 0,0 12를 99로 
x2_sub

array([[99,  5],
       [ 7,  6]])

In [34]:
x2 # x2에도 이미 들어가서 inplace 되어있음 numpy는 ! ..
# 따라서, copy() 통해 만들어야함

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [35]:
x2_sub_copy = x2[:2,:2].copy()

In [36]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [37]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [40]:
# reshape 을 사용한 배열 재구조화

grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# newaxis 이용한 행 변형

x = np.array([1,2,3])
x.reshape((1,3))

x[np.newaxis,:]

array([[1, 2, 3]])

In [50]:
x.reshape((3,1)) 
# or
x[:,np.newaxis] # 어째든 array에 있는 만큼의 행배열 재구성 

array([[1],
       [2],
       [3]])

In [51]:
np.full((3,3), 1.23) # 모든 요소를 지정된 값으로 

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [52]:
np.eye(3) # 단위 행렬임. 정사각이라 길이만 정해주면 됨
# 주 대각선 1, 나머지 0 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.tri(3) # 삼각 행렬

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [55]:
a1 = np.ones(10)

print(a1)
np.zeros_like(a1) # a1을 딴 동일 배열에 0으로! 


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
a3 = np.arange(1,10).reshape(3,3)
a3
np.ones_like(a3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [70]:
np.linspace(0,1,5) # 0 - 1까지 5개 구간
np.logspace(0,1, 20) # 로그값으로 구함 

array([ 1.        ,  1.12883789,  1.27427499,  1.43844989,  1.62377674,
        1.83298071,  2.06913808,  2.33572147,  2.6366509 ,  2.97635144,
        3.35981829,  3.79269019,  4.2813324 ,  4.83293024,  5.45559478,
        6.15848211,  6.95192796,  7.8475997 ,  8.8586679 , 10.        ])

In [71]:
np.random.random((3,3)) 

array([[0.07117895, 0.30465241, 0.3403035 ],
       [0.79227099, 0.14909009, 0.0680513 ],
       [0.7885577 , 0.12169142, 0.05831   ]])

In [74]:
np.random.randint(0, 10, (3,3)) # 정수라 범위 설정 필요 0, 에서 10, 까지 (3,3) 으로

array([[8, 7, 6],
       [5, 2, 1],
       [5, 2, 0]])

In [75]:
np.random.normal(0, 1, (3,3)) # 평균 0, 표평 1, (3,3) 으로

array([[ 0.31183285, -0.68362958,  1.59447302],
       [ 2.55647419, -0.46237141, -0.2049431 ],
       [ 0.18135869,  1.12283851, -0.49318928]])

In [76]:
np.random.rand(3,3) # uniform distribution 균등분포 고려한 랜덤 수 배열

array([[0.74866481, 0.49830674, 0.58613312],
       [0.88963998, 0.98213887, 0.91760635],
       [0.03863721, 0.55339264, 0.55388316]])

In [77]:
np.random.randn(3,3) # 표준정규분포 자동 고려라 3,3 shape만 기재

array([[-1.74300946,  0.24016705, -0.40527358],
       [ 0.00944639,  0.46150735, -2.13798231],
       [-0.03993977,  0.89496611,  0.37165678]])

In [78]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [84]:
date + np.arange(12) # 1월 1일부터 12개         

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [86]:
datetime = np.datetime64('2020-01-01 12:00')
datetime

numpy.datetime64('2020-01-01T12:00')

# 배열 조회

In [92]:
import numpy as np

def array_info(array):
    print(array)
    print("ndim:", array.ndim)
    print("shape:", array.shape)
    print("dtype:", array.dtype)
    print("size:", array.size)
    print("itemsize:", array.itemsize)
    print("nbytes:", array.nbytes)
    print("strides:", array.strides)


In [93]:
a1 = np.array([4,5,6,4,5,6])

In [94]:
array_info(a1)

[4 5 6 4 5 6]
ndim: 1
shape: (6,)
dtype: int64
size: 6
itemsize: 8
nbytes: 48
strides: (8,)


# 인덱싱

In [97]:
print(a1)
print(a1[0]) # 파이썬과 동일하게 사용 가능, 슬라이싱도 ! 

[4 5 6 4 5 6]
4


In [99]:
# 팬시 인덱싱

ind = np.array([[0,1], 
                [2,0]])

print(a1[ind]) # 1차원 배열이지만, 2차원 인덱스 넣으면 2차원으로 반환

[[4 5]
 [6 4]]


# 배열값 삽입/수정/삭제/복사

In [103]:
print(a1)
b1 = np.insert(a1, 0, 10) # a1 array의 0번째 자리에 '10'을 넣어라! 
b1 # a1에 영향 안줌
c1 = np.insert(a1, 2, 10)
c1

[4 5 6 4 5 6]


array([ 4,  5, 10,  6,  4,  5,  6])

In [116]:
a2 = np.arange(1,10).reshape((3,3))
b2 = np.insert(a2, 1, 10, axis=0) # axis 0 : row 기준
b2
c2 = np.insert(a2, 1, 10, axis=1) # axis 1 : column 기준
c2

array([[ 1, 10,  2,  3],
       [ 4, 10,  5,  6],
       [ 7, 10,  8,  9]])

In [122]:
print(a1) 
a1[0] = 1
a1[1] = 2
a1[2] = 3
a1 # 그냥 인덱스로 수정 
a1[:3] = 9 # 슬라이싱 포함 모든 값
a1 
i = np.array([1,3,4]) # array 설정해서
a1[i] = 0 # fancy indexing으로 1,3,4 위치를 0으로 
a1
a1[i] += 4 # 여기도 추가 4 가능 
a1

[9 0 9 0 0 6]


array([9, 4, 9, 4, 4, 6])

In [127]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1 # 첫째 로우 다 1
a2
a2[1:, 2] = 9 # 2,3 row 및 2 col 9로 수정
a2

row = np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0  # row 0,1과 col 1,2 바꿔줘
a2

[[1 1 1]
 [4 2 9]
 [7 8 9]]


array([[1, 0, 1],
       [4, 2, 0],
       [7, 8, 9]])

In [136]:
 # delete() : 배열 특정 위치에 값 삭제
 # axis 지정하지 않으면 1차원 배열로 반환
 # 삭제할 방향을 axis로 지정
 # 원본 배열 변경없이 새로운 배열 변환 
 a1
b1 = np.delete(a1,1)
b1 # a1 그대로 

array([9, 4, 9, 4, 4, 6])

In [139]:
print(a2) 
b2 = np.delete(a2, 1, axis=0) # 4,2,0 사라질 것
b2
c2 = np.delete(a2, 1, axis=1) # 0,2,8 사라질 것
c2

[[1 0 1]
 [4 2 0]
 [7 8 9]]


array([[1, 1],
       [4, 0],
       [7, 9]])

In [142]:
# 배열 변환

print(a2)
print(a2.T) # 행, 열 변환


[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 4 7]
 [0 2 8]
 [1 0 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [143]:
print(a2)
a2.swapaxes(1,0) # T와 같음 

[[1 0 1]
 [4 2 0]
 [7 8 9]]


array([[1, 4, 7],
       [0, 2, 8],
       [1, 0, 9]])