In [1]:
L = list(range(10))

L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]


[bool, str, float, int]

In [22]:
import numpy as np

x = np.arange(10)
x[1:9] # 슬라이싱 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x[1::3] # 1 = 9까지 1부터 3 간격으로 할 때 :: 사용
    

array([1, 4, 7])

In [24]:
x[5::-2] # 5부터 거꾸로 -2씩 빼서 사용

array([5, 3, 1])

In [27]:
x2 = np.array([[12, 5, 2, 4],
                [7, 6, 8, 8],
                [1, 6, 7, 7]])
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
x2_sub = x2[:2, :2]
x2_sub

[[12  5]
 [ 7  6]]


In [33]:
x2_sub[0,0] = 99 # 0,0 12를 99로 
x2_sub

array([[99,  5],
       [ 7,  6]])

In [34]:
x2 # x2에도 이미 들어가서 inplace 되어있음 numpy는 ! ..
# 따라서, copy() 통해 만들어야함

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [35]:
x2_sub_copy = x2[:2,:2].copy()

In [36]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [37]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [40]:
# reshape 을 사용한 배열 재구조화

grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# newaxis 이용한 행 변형

x = np.array([1,2,3])
x.reshape((1,3))

x[np.newaxis,:]

array([[1, 2, 3]])

In [50]:
x.reshape((3,1)) 
# or
x[:,np.newaxis] # 어째든 array에 있는 만큼의 행배열 재구성 

array([[1],
       [2],
       [3]])

In [51]:
np.full((3,3), 1.23) # 모든 요소를 지정된 값으로 

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [52]:
np.eye(3) # 단위 행렬임. 정사각이라 길이만 정해주면 됨
# 주 대각선 1, 나머지 0 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.tri(3) # 삼각 행렬

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [55]:
a1 = np.ones(10)

print(a1)
np.zeros_like(a1) # a1을 딴 동일 배열에 0으로! 


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
a3 = np.arange(1,10).reshape(3,3)
a3
np.ones_like(a3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [70]:
np.linspace(0,1,5) # 0 - 1까지 5개 구간
np.logspace(0,1, 20) # 로그값으로 구함 

array([ 1.        ,  1.12883789,  1.27427499,  1.43844989,  1.62377674,
        1.83298071,  2.06913808,  2.33572147,  2.6366509 ,  2.97635144,
        3.35981829,  3.79269019,  4.2813324 ,  4.83293024,  5.45559478,
        6.15848211,  6.95192796,  7.8475997 ,  8.8586679 , 10.        ])