## 벡터덧셈

In [1]:
u = [1,2,3]
v = [4,5,6]

n = len(u)
w = []

for i in range (0, n):
    val = u[i] + v[i]
    w.append(val)

In [2]:
print(w)

[5, 7, 9]


In [3]:
# def 로 설정

def v_add(u,v):
    n = len(u)
    w = []
    
    for i in range(0, n):
        val = u[i] + v[i]
        w.append(val)
        
    return w
    

## 행렬의 덧셈 / 뺄셈 / 곱셈 / 나눗셈 (모두 동일)

In [8]:
A = [[2,7], [3,4], [6,1]]
B = [[1,4], [4,-1], [2,5]]

n = len(A)
p = len(A[0])

res = []

for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] + B[i][j]
        row.append(val)
    res.append(row)
    
res

[[3, 11], [7, 3], [8, 6]]

In [13]:
C = [[1,4], [5, -2], [3,5]]
D = [[5,2], [0,2], [1,-3]]   
"""
C는 [1,4]
   [5,-2]
    [3,5] 인 2 x 3 행렬임 
    """

r = len(C)
c = len(C[0])
res1 = []
    
for i in range(0, r):
    row = []
    for j in range(0,c):
        val = C[i][j] - D[i][j]
        row.append(val) 
    res1.append(row)

res1


[[-4, 2], [5, -4], [2, 8]]

In [19]:
res2 = [] # 벡터 스칼라 곱 
E = 5

for i in range (0, r):
    row = []
    for j in range (0, c):
        val = E * A[i][j]
        row.append(val)
    res2.append(row)

res2
        
res3 = [] # 행렬 끼리 곱 

for i in range (0, r):
    row = []
    for j in range (0, c):
        val = C[i][j] * D[i][j]
        row.append(val)
    res3.append(row)
    
res3

[[5, 8], [0, -4], [3, -15]]

## 전치행렬 (transposed matrix)

In [33]:
A = [[1,5],[3,4],[6,2]]

r = len(A)
c = len(A[0]) # [1,5] 리스트 개수라 2개

res = []

for i in range(0, c): # 전치해야하니까 행에 넣을 건 열 갯수 
    row = []
    for j in range(0, r):
        val = A[j][i] # i / j  뒤집어 
        row.append(val)
    res.append(row)
    
res

## numpy

import numpy as np

At = np.transpose(A)
print(At)


[[1 3 6]
 [5 4 2]]


행렬 A가 대칭 행렬일 때, 거듭 제곱 또한 대칭 행렬인가 ?

In [34]:
def matmul(A,B):
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])
    
    res = []
    for i in range(0,n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

In [35]:
A = [[1,0,2],[0,2,1],[2,1,1]]

AA = A
for i in range(0,9):
    AA = matmul(AA, A)
    print("행렬 A의", i+2, "제곱은", AA)
    

행렬 A의 2 제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]]
행렬 A의 3 제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]]
행렬 A의 4 제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]]
행렬 A의 5 제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]]
행렬 A의 6 제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]]
행렬 A의 7 제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]]
행렬 A의 8 제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]]
행렬 A의 9 제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]]
행렬 A의 10 제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]]


In [37]:
AA = A

for i in range(0,9):
    AA = np.matmul(AA, A)
    print("행렬 A의", i+2, "제곱은")
    print(AA)
    print("==============")

행렬 A의 2 제곱은
[[5 2 4]
 [2 5 3]
 [4 3 6]]
행렬 A의 3 제곱은
[[13  8 16]
 [ 8 13 12]
 [16 12 17]]
행렬 A의 4 제곱은
[[45 32 50]
 [32 38 41]
 [50 41 61]]
행렬 A의 5 제곱은
[[145 114 172]
 [114 117 143]
 [172 143 202]]
행렬 A의 6 제곱은
[[489 400 576]
 [400 377 488]
 [576 488 689]]
행렬 A의 7 제곱은
[[1641 1376 1954]
 [1376 1242 1665]
 [1954 1665 2329]]
행렬 A의 8 제곱은
[[5549 4706 6612]
 [4706 4149 5659]
 [6612 5659 7902]]
행렬 A의 9 제곱은
[[18773 16024 22416]
 [16024 13957 19220]
 [22416 19220 26785]]
행렬 A의 10 제곱은
[[63605 54464 75986]
 [54464 47134 65225]
 [75986 65225 90837]]


In [ ]:

dd