## 벡터덧셈

In [ ]:
u = [1,2,3]
v = [4,5,6]

n = len(u)
w = []

for i in range (0, n):
    val = u[i] + v[i]
    w.append(val)

In [ ]:
print(w)

In [ ]:
# def 로 설정

def v_add(u,v):
    n = len(u)
    w = []
    
    for i in range(0, n):
        val = u[i] + v[i]
        w.append(val)
        
    return w
    

## 행렬의 덧셈 / 뺄셈 / 곱셈 / 나눗셈 (모두 동일)

In [ ]:
A = [[2,7], [3,4], [6,1]]
B = [[1,4], [4,-1], [2,5]]

n = len(A)
p = len(A[0])

res = []

for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] + B[i][j]
        row.append(val)
    res.append(row)
    
res

In [ ]:
C = [[1,4], [5, -2], [3,5]]
D = [[5,2], [0,2], [1,-3]]   
"""
C는 [1,4]
   [5,-2]
    [3,5] 인 2 x 3 행렬임 
    """

r = len(C)
c = len(C[0])
res1 = []
    
for i in range(0, r):
    row = []
    for j in range(0,c):
        val = C[i][j] - D[i][j]
        row.append(val) 
    res1.append(row)

res1


In [ ]:
res2 = [] # 벡터 스칼라 곱 
E = 5

for i in range (0, r):
    row = []
    for j in range (0, c):
        val = E * A[i][j]
        row.append(val)
    res2.append(row)

res2
        
res3 = [] # 행렬 끼리 곱 

for i in range (0, r):
    row = []
    for j in range (0, c):
        val = C[i][j] * D[i][j]
        row.append(val)
    res3.append(row)
    
res3

## 전치행렬 (transposed matrix)

In [ ]:
A = [[1,5],[3,4],[6,2]]

r = len(A)
c = len(A[0]) # [1,5] 리스트 개수라 2개

res = []

for i in range(0, c): # 전치해야하니까 행에 넣을 건 열 갯수 
    row = []
    for j in range(0, r):
        val = A[j][i] # i / j  뒤집어 
        row.append(val)
    res.append(row)
    
res

## numpy

import numpy as np

At = np.transpose(A)
print(At)


행렬 A가 대칭 행렬일 때, 거듭 제곱 또한 대칭 행렬인가 ?

In [ ]:
def matmul(A,B):
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])
    
    res = []
    for i in range(0,n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

In [ ]:
A = [[1,0,2],[0,2,1],[2,1,1]]

AA = A
for i in range(0,9):
    AA = matmul(AA, A)
    print("행렬 A의", i+2, "제곱은", AA)
    

In [ ]:
AA = A

for i in range(0,9):
    AA = np.matmul(AA, A)
    print("행렬 A의", i+2, "제곱은")
    print(AA)
    print("==============")

## 대각행렬
대각 성분 제외한 나머지는 0

In [4]:
A = [[1,2,3],[4,5,6],[7,8,9]]

n = len(A)
D = []

for i in range(0,n):
    row = []
    for j in range(0,n):
        if i == j:
            row.append(A[i][j])
        else:
            row.append(0)
    D.append(row)
    
    

[[1, 0, 0]]
[[1, 0, 0], [0, 5, 0]]
[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


In [20]:
# numpy 이용
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A,"\n")
A_dia = np.diag([1,2,3])
A_dia

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
AD = np.matmul(A,A_dia)
AD #대각행렬이 뒤이면, col 기준으로 곱

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [19]:
DA = np.matmul(A_dia, A)
DA # 대각행렬이 앞이면, row 기준 곱 

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

## 단위행렬
주대각이 1이고, 나머지는 모두 0, 기호로 I (Identity matrix)
특정 행렬 A에 대해, AI = IA = A 

In [22]:
def identity (n):
    I = []
    for i in range (0,n):
        row = []
        for j in range (0,n):
            if i == j:
                row.append(1)
            else: 
                row.append(0)
        I.append(row)
    
    return I 

identity(5)

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [26]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A, "\n")

I = identity(3)
print(I, "\n") 

AI = np.matmul(A,I)
IA = np.matmul(I,A)

print(AI, "\n")
print(IA, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1, 0, 0], [0, 1, 0], [0, 0, 1]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



## 삼각 행렬 (triangular matrix)
구성 원소가 삼각형 형태 - upper triangular matrix, lower triangular matrix

In [31]:
A = [[1,2,3], [4,5,6], [7,8,9]]

n = len(A) # 3
p = len(A[0]) # 3

utri = []

for i in range (0, n):
    row = []
    for j in range (0, p):
        if i > j: # lower triangular 는 i < j 로 하면 됨 
            row.append(0)
        else: 
            row.append(A[i][j])
    utri.append(row)

np.array(utri)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [34]:
# 넘파이

A = np.array([[1,2,3], [4,5,6], [7,8,9]])

Au = np.triu(A)
Al = np.tril(A)
print(Au, "\n")
print(Al)

[[1 2 3]
 [0 5 6]
 [0 0 9]] 

[[1 0 0]
 [4 5 0]
 [7 8 9]]


## 토플리츠 행렬 (Toeplitz matrix)


In [38]:
a = [1,0,-2,-4]
b = [1,3,5,7,9]

In [36]:
n1 = len(a)
n2 = len(b)


4
5


In [41]:
A = []

for i in range(0, n1):
    row = []
    for j in range (0, n2):
        if i > j:
            row.append(a[i-j])
        else:
            row.append(b[j-i])
    A.append(row)

np.array(A)

array([[ 1,  3,  5,  7,  9],
       [ 0,  1,  3,  5,  7],
       [-2,  0,  1,  3,  5],
       [-4, -2,  0,  1,  3]])

In [43]:
## scipy 사용

from scipy.linalg import toeplitz
A = toeplitz([1,0,-2,-4],[1,3,5,7,9])
print(A)

[[ 1  3  5  7  9]
 [ 0  1  3  5  7]
 [-2  0  1  3  5]
 [-4 -2  0  1  3]]


## 이중 대각 행렬 bidiagonal matrix
대각 원소 위/아래 (upper/lower bidiagonal matrix) 성분도 0이 아닌 대각 행렬

In [45]:
A = [[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]]
n = len(A)
p = len(A[0])

In [49]:
res = []
for i in range (0,n): 
    row = []
    for j in range (0,p):
        if i > j or j-i > 1: 
            row.append(0)
        else:
            row.append(A[i][j])
    res.append(row)

print(np.array(A), "\n")
print(np.array(res))

[[1 2 1 3]
 [5 3 4 1]
 [2 1 7 9]
 [2 8 1 3]] 

[[1 2 0 0]
 [0 3 4 0]
 [0 0 7 9]
 [0 0 0 3]]


In [54]:
## numpy
diag_ele = np.diag(A)
print(diag_ele, "\n")
np.diag(diag_ele)

u_diag_ele = np.diag(A, k=1)
print(u_diag_ele)

np.diag(u_diag_ele, k=1)

[1 3 7 3] 

[2 4 9]


array([[0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 9],
       [0, 0, 0, 0]])

## householder 행렬 (Householder matrix)
- 어떤 행렬을 다른 형태로 변환할 때 사용하는 행렬 
- 정사각 행렬이며, 모든 열이 정규 직교 (orthonomal) 임

v = ([v1],
    [v2],
    [v3],
    [v4]]) 
    일 때 ,

H = I - 2 * vvT/vTv  
vvT = 내적
vTv = 외적

In [ ]:
def outer_product(a,b):
    res = []
    n1 = len(a)
    n2 = len(b)
    for i in range(0,n1):
        row =[]
        for j in range (0, n2):
            val = a[i]*b[j]
            row.append(val)
        res.append(row)
    return res

In [ ]:
def inner_product(a,b):
    res = []
    n = len(a)
    res = 0
    for i in range(0,n):
        res += a[i]*b[i]
    return res

In [63]:
def subtract(A,B):
    n = len(A)
    p = len(A[0])
    
    res = []
    for i in range(0,n):
        row = []
        for j in range(0,p):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    return res

In [64]:
def householder(v):
    n = len(v)
    outer_mat = outer_product(v,v)
    inner_val = inner_product(v,v)
    V = []
    for i in range(0,n):
        row = []
        for j in range(0, n):
            val = (2/inner_val)*outer_mat[i][j]
            row.append(val)
        V.append(row)
    H = subtract(identity(n),V)
    return H

In [65]:
a = [1,0,2,3]

householder(a)

[[0.8571428571428572, 0.0, -0.2857142857142857, -0.42857142857142855],
 [0.0, 1.0, 0.0, 0.0],
 [-0.2857142857142857, 0.0, 0.4285714285714286, -0.8571428571428571],
 [-0.42857142857142855, 0.0, -0.8571428571428571, -0.2857142857142856]]

#  선형 시스템 해 구하기

In [71]:
X = [[3,1,2], [2,6,-1], [4,0,-1]]
y = [5,1,3]

x0 = X[0]
x1 = X[1]
x2 = X[2]

y0 = y[0]
y1 = y[1]
y2 = y[2]

print('원본행렬')
print(x0, y0)
print(x1, y1)
print(x2, y2)


원본행렬
[3, 1, 2] 5
[2, 6, -1] 1
[4, 0, -1] 3


In [72]:
import numpy as np

def solve(A, b):
    X = deepcopy(A)
    sol = deepcopy(b) 
    n = len(X)
    
    for i in range(0,n):
        print("-----i번째 실행 시작-----")
        x_row = X[i]
        y_val = sol[i]
        
        if x_row[i] != 0:
            tmp = 1/x_row[i]
        else:
            tmp = 0
        
        x_row = [element*tmp for element in x_row]
        y_val = y_val*tmp
        
        X[i] = x_row
        sol[i] = y_val
        
        print(x_row)
        print(y_val)
        print('-----행 나누기 완료-----')
        
        for j in range(0,n):
            if i == j:
                continue
            print('-----j번째 실행 시작-----')
            x_next = X[j]
            y_next = sol[j]
            x_tmp = [element * -x_next[i] for element in x_row]
            
            y_tmp = y_val*(-x_next[i])
            for k in range(0, len(x_row)):
                x_next[k] = x_tmp[k] + x_next[k]
            y_next = y_tmp + y_next
            
            X[j] = x_next
            sol[j] = y_next
            
            print(X)
            print(sol)
            print('-----j번째 실행 종료-----')
            
        print('i번째 실행 완료')
        
    return sol 

In [73]:
solve(X,y)

NameError: name 'deepcopy' is not defined